### ISSUE TITLE
Crash (blood bank API/entity)

### ISSUE THREAD

**Issue by Cat-McCatface** [palaster/BloodBank#6]
Downloaded current to test is issues around spawned skel (burning in daylight) was worked on (and suitability for modpack in general). Made new test world and opened inventory to view items. Crash occurred without interaction with items or world.

mod version: 0.6.1
MC: 1.9.4
forge: 1954
log: http://pastebin.com/iJH39NSu

**Comment by palaster** [comment]
Did you kill anything or see anything get killed at the time of the crash?

**Comment by Cat-McCatface** [comment]
nope. it happened within the first minuet of player control.

**Comment by palaster** [comment]
What kind of world was it normal or superflat?

**Comment by palaster** [comment]
Also, are you playing with other mods?

**Comment by Cat-McCatface** [comment]
normal world generation, no mods that alter (other than ores/trees). a partial modpack is used as part of the test bed.

**Comment by palaster** [comment]
Is this the first time it has happened or has it happened multiple times.

**Comment by Cat-McCatface** [comment]
tested again with new world (and recording with obs) and it happens regardless of player activity (or even wolf activity as entity referred to this time can't attack other mobs)
log: http://pastebin.com/DXuqmUdL
video (excuse low bitrate) https://youtu.be/VV22adfY6n4

**Comment by palaster** [comment]
Alright, I just uploaded a new file to curseforge, Blood Bank-0.6.2.jar, can you try it and see if your getting the same issue.

**Comment by Cat-McCatface** [comment]
0.6.2 seems to have fixed it (although would have to play test the intended function/collect blood from some vict.. mobs)

**Comment by palaster** [comment]
Alright that is good to hear, if you the issue pops up again please let me know.
